name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  internal_test:
    name: Internal test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features
